// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
)

type Account struct {
	AccountID    sql.NullString `json:"account_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	IsSubscribe  sql.NullBool   `json:"is_subscribe"`
}

type VehicleDatum struct {
	VID         string         `json:"v_id"`
	AccountID   sql.NullString `json:"account_id"`
	PlateNumber sql.NullString `json:"plate_number"`
}
